FROM alpine:3.13

# Add requirements.txt
ADD requirements.txt /tmp

# Install necessary packages and dependencies
RUN apk update && \
    apk add --no-cache libffi openssl python3 py3-pip && \
    apk add --no-cache --virtual .build-deps gcc musl-dev python3-dev libffi-dev openssl-dev && \
    pip install pip==21.0.1 --upgrade && \
    pip install wheel==0.36.2 && \
    pip3 install -r /tmp/requirements.txt --ignore-installed six && \
    apk del .build-deps && \
    rm -f /var/cache/apk/*

# Add the lookout script
ADD lookout.py /root

# Set the entrypoint
ENTRYPOINT ["python3", "-u", "/root/lookout.py"]
